### ISSUE TITLE
Missing parts

### ISSUE THREAD

**Issue by gen4sp** [newflight-co/createvid#1]
I've tried to run the project, but there is no `templates.js` included, but required.
Also, I haven't find a docker file for the worker.
Could you assist me with those issues?

Thank you!

**Comment by timo9000** [comment]
Let me track down the template.js, I might need to strip out all our client info first which is why it's not included. The worker was running in Paperspace which doesn't allow docker services so we just ran a script on startup to start the worker. If you'd like to add one please make a PR we can include.

Thanks for letting us know!

**Comment by timo9000** [comment]
@gen4sp I've added an example template file under config/ let me know how you get on.

**Comment by gen4sp** [comment]
@timo9000 thank you! will check it out soon

**Comment by gen4sp** [comment]
You've made a mistake. Should be `templateS.js` not `template.js`
I've just renamed the file, but still get an error:
```
frontend: This relative module was not found:
frontend: * ./templates in ./src/store/index.js
```

Seems it is another one?

**Comment by timo9000** [comment]
Ah yea, we have a Vuex store with some data in it to remove. Leave it with us, we'll commit a working version tested from scratch as I'm getting other errors after adding ti back in. Thanks for your patience.

**Comment by gen4sp** [comment]
@timo9000 could you say when I can expect the new commit? 
Thank you

**Comment by gen4sp** [comment]
@timo9000 any news?

**Comment by timo9000** [comment]
Hey sorry, we are finding resources to fix it, bear with us a little longer and we will get it working.

**Comment by gen4sp** [comment]
Great! looking forward!

**Comment by gen4sp** [comment]
Sorry for disturbing you, but any updates here?
Maybe I can help you somehow?
Thank you

**Comment by timo9000** [comment]
Can you send me your email? I’ll see if we can help with my working version

**Comment by gen4sp** [comment]
sure
gen4maili@gmail.com

**Comment by timo9000** [comment]
I got a bounce back from that email, can you check?

**Comment by gen4sp** [comment]
yes, sorry, misprint

gen4mail@gmail.com

**Comment by Kperroch** [comment]
@gen4sp do you have this issue on the worker and server when starting ?
```
server: [PATH]\createvid\packages\common\src\channel.js:8
server:   listeners = {};
server: SyntaxError: Unexpected token =
server:     at new Script (vm.js:83:7)
server:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by gen4sp** [comment]
no, I have not

**Comment by Kperroch** [comment]
Which version of node are you using ?
thanks in advance

**Comment by gen4sp** [comment]
12.14.0
